### ISSUE TITLE
don't use hard-coded pathes

### ISSUE THREAD

**Issue by szabgab** [danieldeitch1/wis_python_ML#1]
Having hard-coded pathes such as
```
data_path = r'C:\Users\rotaition\Desktop\wis_python'
```
makes it impossible to use the code elsewhere.

**Comment by danieldeitch1** [comment]
Done.
I used the command "os.path.dirname(__file__)" in order to define the path and relative paths of the different files required to run the script.
The only assumption is that the data ("neuronal_data.npy" and "trial_info.npy") and the script containing the functions ("ensemble_rate_corr.py") are in the same folder as the main script ("visual_spatial_nav_ML.py").
This is indeed the case if you just clone the entire repository.

If it is still not good enough, I would like to get a clue about the correct solution for this problem.  

Thank you.

**Comment by szabgab** [comment]
That's a good solution for this case.
